### ISSUE TITLE
White background at chat enable/disable

### ISSUE THREAD

**Issue by TheMadRuffian** [mxdanger/GoogleMeet-Dark#1]
Hi!

I really appreciate your work. Saves me from getting strokes. Enjoying it to the fullest. Thanks a lot.

There is this white background, which seems off, at the place where the room chat is enabled/disabled.
![Screenshot 2021-01-12 at 23 55 01](https://user-images.githubusercontent.com/42994263/104338922-02490e00-5532-11eb-82a1-8e524ec0998c.png)

**Comment by mxdanger** [comment]
That option is limited to just G Suite users [(Google support link)](https://support.google.com/meet/answer/9308979), and I do not have any G Suite for Education accounts that I can use for creating meetings, so I won't be able to fix this unless someone else made a pull request with the fix. Alternatively, if you know the html class for that element, I should be able to fix it.

**Comment by TheMadRuffian** [comment]
I understand.

I think I can help with finding the html class. The following seems to be the code that is specific to that element. Please feel free to ask for more code if necessary.

`<div class="WAPtFd jE2Fge" jsaction="JIbuQc:HNzTd;L3AHvb:xMvh5c;ukb9dc:o7OeQe" jscontroller="EZrd9c" data-is-persistent="true"><div class="IEJ9Nd snByac" aria-hidden="true">Let everyone send messages</div><div jscontroller="yRgwZe" jsaction="click:cOuCgd; mousedown:UX7yZ; mouseup:lbsD7e; mouseenter:tfO1Yc; mouseleave:JywGue; touchstart:p6p2H; touchmove:FwuNnf; touchend:yfqBxc; touchcancel:JMtRjd; contextmenu:mg9Pef" class="VfPpkd-scr2fc VfPpkd-scr2fc-OWXEXe-barxie LXctle pBHsAc ubzCcb" jsname="ilpChd"><div class="VfPpkd-l6JLsf"></div><div jsname="aLJec" class="VfPpkd-yNh9Ed-aLJec"><div class="VfPpkd-yNh9Ed"></div><input jsname="YPqjbf" jsaction="focus:AHmuwe; blur:O22p3e; change:WPi0i" type="checkbox" class="VfPpkd-e9dDuf-bMcfAe" role="switch" aria-label="Let everyone send messages" checked="" aria-checked="true"></div></div></div>`

![Screenshot 2021-01-13 at 07 22 04](https://user-images.githubusercontent.com/42994263/104386393-101d8400-5570-11eb-8da9-637e005cfee0.png)

**Comment by TheMadRuffian** [comment]
The code for the switch seems to be the following.

`<input jsname="YPqjbf" jsaction="focus:AHmuwe; blur:O22p3e; change:WPi0i" type="checkbox" class="VfPpkd-e9dDuf-bMcfAe" role="switch" aria-label="Let everyone send messages" checked="" aria-checked="true">`

![Screenshot 2021-01-13 at 07 26 05](https://user-images.githubusercontent.com/42994263/104386776-c4b7a580-5570-11eb-9712-5eb9d84fca59.png)

**Comment by mxdanger** [comment]
Create a new style and add this to it and let me know if that changes the color of the white background.
```css
@-moz-document domain("meet.google.com") {
    .WAPtFd.jE2Fge {
        background-color: #202124;
    }
}
```

**Comment by TheMadRuffian** [comment]
Yes, it changes the color of the white background. Although the text is black, when the publicly released version is added, it looks as one would expect.

No style:
![Screenshot 2021-01-13 at 08 00 05](https://user-images.githubusercontent.com/42994263/104388964-6214d880-5575-11eb-9493-50a8128d788e.png)

Style with the code in previous comment:
![Screenshot 2021-01-13 at 08 01 07](https://user-images.githubusercontent.com/42994263/104389030-85d81e80-5575-11eb-9aa8-abda04da71b1.png)

Publicly released style + style with the code in previous comment:
![Screenshot 2021-01-13 at 08 02 27](https://user-images.githubusercontent.com/42994263/104389132-b455f980-5575-11eb-87af-258f7c769b95.png)

**Comment by mxdanger** [comment]
I just realized I could copy and paste the html you sent earlier and add it to the page to test it myself. This is what it looks like now.
![image](https://user-images.githubusercontent.com/32040254/104390871-892ac600-54f3-11eb-978b-9f7fc6b80cca.png)
Thanks for making the bug report, I'll publish the changes shortly.
