### ISSUE TITLE
Conflict with Google Meet Grid View (fix) extension

### ISSUE THREAD

**Issue by leandroprz** [mxdanger/GoogleMeet-Dark#3]
**Device Information**
 - **Operating System:** Windows 10 x64 Pro
 - **Browser:** Chrome v87.0.4280.141

**Describe the bug**
When trying to use this style along with [this extension](https://chrome.google.com/webstore/detail/google-meet-grid-view-fix/dakebdbeofhmlnmjlmhjdmmjmfohiicn?hl=en) there's a conflict between them and the Grid extension doesn't work properly. It shows only 1 participant.

**Comment by mxdanger** [comment]
My style is written _only_ in CSS so anything relating to JS such as only displaying one participant is out of my control. That and the arrangement and styling of the actual grid is what I have left completely untouched.
